import Config

# Load environment variables from .env file
# Only load if Dotenvy is available (after deps.get)
if Code.ensure_loaded?(Dotenvy) and File.exists?(".env") do
  Dotenvy.source!(".env")
end

# Configure your database
config :assetronics, Assetronics.Repo,
  username: "marcinwalczak",
  password: "",
  hostname: "localhost",
  database: "assetronics_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  # Reduced pool size to avoid Postgrex type loading race condition
  pool_size: 2

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :assetronics, AssetronicsWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "IcLO/9UxesjYWJy9Ykf4r/N1ttBnPrnpp/C8zj45jA9qbXI2VX+nzVaVjzEbVKol",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :assetronics, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# File storage configuration (local storage for development)
config :assetronics,
  storage_provider: :local,
  upload_path: "priv/static/uploads"

# Email configuration for development
config :assetronics,
  from_email: System.get_env("FROM_EMAIL") || "noreply@localhost",
  from_name: System.get_env("FROM_NAME") || "Assetronics Dev",
  support_email: System.get_env("SUPPORT_EMAIL") || "support@localhost",
  app_url: System.get_env("APP_URL") || "http://localhost:3000"
